import axios from "axios";
import React, { useState } from "react";
import { setUserSession } from "./service/AuthService";
const LoginAPIUrl =
  " https://s9tme76mge.execute-api.eu-central-1.amazonaws.com/BU2_Ecommerce/login";

/*
 ** IMPORTANT change this URL to your AWS Api login URL
 */
const Login = (props) => {
  const [typeId, setTypeId] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [errorMessage, setErrorMessage] = useState(null);

  const submitHandler = (event) => {
    event.preventDefault();
    if (username === "" || password === "" || typeId === "") {
      setErrorMessage("Both username and password are required");
      return;
    }
    setErrorMessage(null);
    const requestConfig = {
      headers: {
        "x-api-key": "O8vHCdfPJQ3kdEsvIEUZh4OSgfOgomIZ8beWa0uP",
      },
    };
    /*
     ** Change api-key >> its autogenerated from aws console -> api gateway
     */
    const requestBody = {
      typeId: typeId,
      username: username,
      password: password,
    };

    axios
      .post(LoginAPIUrl, requestBody, requestConfig)
      .then((respose) => {
        setUserSession(respose.data.user, respose.data.token);
        props.history.push("/premium-content");
      })
      .catch((error) => {
        if (error.response.status === 401 || error.response.status === 403) {
          setErrorMessage(error.response.data.message);
        } else {
          setErrorMessage(
            "sorry... the backend server is down.please try again later"
          );
        }
      });
  };

  return (
    <div>
      <form onSubmit={submitHandler}>
        <h5>Login</h5>
        typeId:{" "}
        <input
          type="text"
          value={typeId}
          onChange={(event) => setTypeId(event.target.value)}
        ></input>{" "}
        <br />
        username:{" "}
        <input
          type="text"
          value={username}
          onChange={(event) => setUsername(event.target.value)}
        ></input>{" "}
        <br />
        password:{" "}
        <input
          type="password"
          value={password}
          onChange={(event) => setPassword(event.target.value)}
        ></input>{" "}
        <br />
        <input type="submit" value="Login" />
      </form>
      {errorMessage && <p className="message">{errorMessage}</p>}
    </div>
  );
};

export default Login;
